import {
  Accessibility,
  Activity,
  Apple,
  Armchair,
  Backpack,
  BadgeDollarSign,
  Banknote,
  Bath,
  Bed,
  Beer,
  Bell,
  Bike,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Bug,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Carrot,
  CarTaxiFront,
  ChefHat,
  Cigarette,
  CircleEllipsis,
  Clapperboard,
  Clock,
  Cloud,
  Coffee,
  Coins,
  Compass,
  Cookie,
  CreditCard,
  CupSoda,
  Dices,
  DoorOpen,
  Droplets,
  Dumbbell,
  Earth,
  EggFried,
  Eye,
  Fan,
  Fence,
  FileText,
  Film,
  Fish,
  Flashlight,
  Flower2,
  Folder,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Hammer,
  Hand,
  HandCoins,
  HandHeart,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  IceCream,
  KeyRound,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  LineChart,
  Luggage,
  Mail,
  Map,
  MapPin,
  Medal,
  Mic,
  Microscope,
  Microwave,
  Monitor,
  Moon,
  MoreHorizontal,
  Mountain,
  Music,
  Music2,
  Navigation,
  Network,
  NotebookPen,
  Paintbrush,
  Palette,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  Pen,
  Pencil,
  Phone,
  Piano,
  PieChart,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Plus,
  Popcorn,
  Presentation,
  Printer,
  Receipt,
  Refrigerator,
  Rocket,
  Sailboat,
  Sandwich,
  Scale,
  Scan,
  School,
  Scissors,
  Settings,
  Shield,
  Ship,
  Shirt,
  Shovel,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Smile,
  Sofa,
  Sparkle,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  Tag,
  Target,
  Tent,
  Theater,
  Thermometer,
  Ticket,
  TrafficCone,
  TrainFront,
  TreePine,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Video,
  Wallet,
  Watch,
  Waves,
  Wind,
  Wine,
  Wrench,
  Zap,
  Baby,
  type LucideIcon,
} from 'lucide-react';
import { ALL_CATEGORY_ICON_KEYS, DEFAULT_CATEGORY_ICON_KEY } from '../../domain/categories/categoryIconLibrary';

export const CATEGORY_ICON_REGISTRY: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  activity: Activity,
  apple: Apple,
  armchair: Armchair,
  backpack: Backpack,
  'badge-dollar-sign': BadgeDollarSign,
  banknote: Banknote,
  bath: Bath,
  bed: Bed,
  beer: Beer,
  bell: Bell,
  binoculars: Scan,
  bird: Bug,
  bike: Bike,
  book: Book,
  'book-open': BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  'building-2': Building2,
  bug: Bug,
  bus: Bus,
  cake: Cake,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  camping: Tent,
  car: Car,
  carrot: Carrot,
  'car-taxi-front': CarTaxiFront,
  'chart-line': LineChart,
  'chart-pie': PieChart,
  'chef-hat': ChefHat,
  cigarette: Cigarette,
  'circle-ellipsis': CircleEllipsis,
  clapperboard: Clapperboard,
  clock: Clock,
  cloud: Cloud,
  coffee: Coffee,
  coins: Coins,
  compass: Compass,
  cookie: Cookie,
  'credit-card': CreditCard,
  'cup-soda': CupSoda,
  dices: Dices,
  'door-open': DoorOpen,
  droplets: Droplets,
  dumbbell: Dumbbell,
  earth: Earth,
  'egg-fried': EggFried,
  eye: Eye,
  fan: Fan,
  fence: Fence,
  'file-text': FileText,
  film: Film,
  fish: Fish,
  flashlight: Flashlight,
  'flower-2': Flower2,
  folder: Folder,
  footprints: Footprints,
  fuel: Fuel,
  'gamepad-2': Gamepad2,
  gem: Gem,
  gift: Gift,
  glasses: Glasses,
  globe: Globe,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  hand: Hand,
  'hand-coins': HandCoins,
  'hand-heart': HandHeart,
  hanger: Shirt,
  headphones: Headphones,
  heart: Heart,
  'help-circle': HelpCircle,
  home: Home,
  hospital: Building2,
  'ice-cream-cone': IceCream,
  'key-round': KeyRound,
  lamp: Lamp,
  landmark: Landmark,
  languages: Languages,
  laptop: Laptop,
  leaf: Leaf,
  library: Library,
  lightbulb: Lightbulb,
  lipstick: Sparkles,
  luggage: Luggage,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  medal: Medal,
  mic: Mic,
  microscope: Microscope,
  microwave: Microwave,
  monitor: Monitor,
  moon: Moon,
  'more-horizontal': MoreHorizontal,
  motorbike: Bike,
  mountain: Mountain,
  music: Music,
  'music-2': Music2,
  navigation: Navigation,
  network: Network,
  'notebook-pen': NotebookPen,
  'paint-bucket': Paintbrush,
  palette: Palette,
  'parking-circle': ParkingCircle,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  pen: Pen,
  pencil: Pencil,
  phone: Phone,
  piano: Piano,
  'piggy-bank': PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  plug: Plug,
  plus: Plus,
  popcorn: Popcorn,
  presentation: Presentation,
  printer: Printer,
  receipt: Receipt,
  refrigerator: Refrigerator,
  rocket: Rocket,
  sailboat: Sailboat,
  sandwich: Sandwich,
  scale: Scale,
  school: School,
  scissors: Scissors,
  settings: Settings,
  shield: Shield,
  ship: Ship,
  shirt: Shirt,
  shovel: Shovel,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  smile: Smile,
  sock: Shirt,
  sofa: Sofa,
  sparkle: Sparkle,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  syringe: Syringe,
  tag: Tag,
  target: Target,
  tent: Tent,
  theater: Theater,
  thermometer: Thermometer,
  ticket: Ticket,
  'traffic-cone': TrafficCone,
  'train-front': TrainFront,
  'tree-pine': TreePine,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  umbrella: Umbrella,
  user: User,
  users: Users,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  video: Video,
  volleyball: Target,
  wallet: Wallet,
  watch: Watch,
  waves: Waves,
  wind: Wind,
  wine: Wine,
  wrench: Wrench,
  zap: Zap,
  baby: Baby,
  bandage: Shield,
};

export function getCategoryIconComponent(iconKey: string): LucideIcon {
  return CATEGORY_ICON_REGISTRY[iconKey] ?? CATEGORY_ICON_REGISTRY[DEFAULT_CATEGORY_ICON_KEY];
}

/** Dev-time guard: every library key must resolve to a component. */
export function assertCategoryIconRegistryComplete(): void {
  for (const key of ALL_CATEGORY_ICON_KEYS) {
    if (!CATEGORY_ICON_REGISTRY[key]) {
      throw new Error(`Missing icon registry entry for ${key}`);
    }
  }
}
